/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sistemaadministrador.br.edu.ifpb.esperanca.padroes.editais;
import java.util.Scanner;

import sistemaadministrador.br.edu.ifpb.esperanca.padroes.editais.command.CreateStudentAccount;
import sistemaadministrador.br.edu.ifpb.esperanca.padroes.editais.command.DisableStudentAccount;
import sistemaadministrador.br.edu.ifpb.esperanca.padroes.editais.command.LoginAdmin;
import sistemaadministrador.br.edu.ifpb.esperanca.padroes.editais.command.SearchStudent;
import sistemaadministrador.br.edu.ifpb.esperanca.padroes.editais.command.UpdateStudent;
import sistemaadministrador.br.edu.ifpb.esperanca.padroes.editais.command.ViewStudentList;
import sistemaadministrador.br.edu.ifpb.esperanca.padroes.editais.manager.Controller;

public class App {
    Controller controller = new Controller();
    
    public void menuPrincipal() {
        Scanner scanner = new Scanner(System.in);

        LoginAdmin verifyAdmin = new LoginAdmin(controller);
        verifyAdmin.executeLoginAdmin();

        int op = -1;

        while (op != 6) {
            exibirMenu();
            System.out.print("Digite a opção: ");
            op = scanner.nextInt();
            System.out.println();

            switch (op) {
                case 1:
                    CreateStudentAccount createStudentAccount = new CreateStudentAccount(controller);
                    createStudentAccount.executeCreateStudentAccount();
                    break;
                case 2:
                    ViewStudentList viewStudentList = new ViewStudentList(controller);
                    viewStudentList.executeviewStudentList();
                    break;
                case 3:
                    SearchStudent searchStudent  = new SearchStudent(controller);
                    searchStudent.executeSearchStudent();
                    break;
                case 4:
                    DisableStudentAccount disableStudentAccount = new DisableStudentAccount(controller);
                    disableStudentAccount.executeDisableStudentAccount();
                    break;
                case 5:
                    UpdateStudent updateStudent = new UpdateStudent(controller);
                    updateStudent.executeUpdateStudent();
                    break;
                case 6:
                    System.out.println("Saindo do sistema...");
                    break;
                default:
                    System.out.println("Opção inválida.");
                    break;
            }
        }
        scanner.close();
    }

    private void exibirMenu() {
        System.out.println("----------------------------- Menu Principal -----------------------------");
        System.out.println("1. Criar conta de aluno");
        System.out.println("2. Visualizar lista de alunos");
        System.out.println("3. Procurar aluno");
        System.out.println("4. Desativar conta de aluno");
        System.out.println("5. Atualizar dados do aluno");
        System.out.println("6. Sair do sistema");
        System.out.println("--------------------------------------------------------------------------");
    }

    public static void main(String[] args) {
        App app = new App();
        app.menuPrincipal();
    }
}

